# This notebook should run fine

This notebook should run just fine

In [8]:
import numpy as np

v1=np.array([[1,2,3]])
v2=np.array([7])

# and now we see the magic of broadcasting
v1 + v2

array([[ 8,  9, 10]])

In [10]:
(v1 + v2).T @ v1

array([[ 8, 16, 24],
       [ 9, 18, 27],
       [10, 20, 30]])

In [13]:
((v1 + v2) @ v1.T).reshape(-1,)

array([56])